language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '8'
before_install:
  - npm install -g npm
  - npm install -g greenkeeperio/greenkeeper-lockfile#feat/monorepos
before_script: greenkeeper-lockfile-update
