language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '7'
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@greenkeeperio/feat/monorepos#feat/monorepos
before_script: greenkeeper-lockfile-update
